### ISSUE TITLE
Configure "full_message" field

### ISSUE THREAD

**Issue by pedroxs** [mp911de/logstash-gelf#110]
Is there a way to set the entire JSON message as the "full_message" field? I am using version 1.11.0 and logback apender.

**Comment by mp911de** [comment]
I'm not sure I follow. Could you describe your request a bit in detail or post a sample how the JSON should look like? Please keep in mind that GELF demands `full_message`  to be a `string (UTF-8)`.

**Comment by pedroxs** [comment]
I was using the following [appender](https://github.com/Moocar/logback-gelf) but since it is no longer maintained I found yours to be a best solution. With the previous one the field `full_message` is a `string (UTF-8)` that contains the complete message body sent to GELF as a JSON string.

Example JSON:
```
{"@timestamp":"2017-03-09T16:17:35.562-03:00","@version":1,"message":"The Reconcile hashcodes after complete sync up, client : UP_170_, server : UP_176_.","logger_name":"com.netflix.discovery.DiscoveryClient","thread_name":"pool-8-thread-4","level":"WARN","level_value":30000,"HOST":"live-risk-hostname","REMOTE_HOST":"some-hostname.local","HOSTNAME":"prd-bb8-app03"}
```

My questions is if this is possible with your appender?

**Comment by mp911de** [comment]
Thanks for the reference, it helped me a lot to understand the actual issue. The short answer is no.

Explanation:

`logback-gelf` uses a `PatternLayout` to construct `full_message`. `logstash-gelf` uses just the message from the underlying log event and stores it in the full message field. 

Additional fields are configurable and sent individually to the GELF target. This is because of various reasons. The main reason is that the log appender should not have any smartness regarding message construction but the right place to alter the message is on the GELF receiver side (at least for logstash). Otherwise, you're required to configure each application to format messages the same way which is way more configuration overhead than maintaining a central instance of message transformation.

**Comment by mp911de** [comment]
May I close this ticket or is there anything else I can assist you with?

**Comment by pedroxs** [comment]
Sure, I should have closed this already. Thanks for the support.
