### ISSUE TITLE
Gelf-Logger Thread consuming lots of CPU

### ISSUE THREAD

**Issue by Magublafix** [mp911de/logstash-gelf#123]
Hi,

Last week I recognized high CPU consumption by the Gelf thread, where most of the cpu time is spent in Unsafe.park().

According to https://stackoverflow.com/questions/12972918/why-does-park-unpark-have-60-cpu-usage, I watched the context switches of the gelf thread which showed a lot of  context switches:

```
Every 5,0s: grep ctxt /proc/21532/status                                                                              Tue Nov 14 14:46:48 2017

voluntary_ctxt_switches:        902773
nonvoluntary_ctxt_switches:     3786
```

Any suggestions how to fix that behaviour?

regards,
Gerald

**Comment by mp911de** [comment]
Could you be more specific and provide some stack traces showing park state? Also, logstash-gelf does not spin up own threads but operates on the threads that the logger is configured/invoked with.

**Comment by Magublafix** [comment]
Hi @mp911de ,

That was fast, I'm still collecting the data ;)
I'll upload the thread dump in a few minutes.

We are using dynatrace and saw  that one thread (pool-5-thread-1) is using a lot of cpu within a cpu sample. During the CPU Sample the stack looks like this (only cut version, I can attach the dynatrace file if you have a dynatrace client installed? it's free)

![20171114_cpusample](https://user-images.githubusercontent.com/4953529/32785411-bdf1a7ea-c951-11e7-93d5-20711bfccab8.PNG)

I'm not a developer and assumed that logstash-gelf is running on it's own thread, because there was no other activity than the park and JBoss7GelfLogHandler.publish().
So maybe I have to look somewhere else for the problem? What do you think?

regards,
Gerald

**Comment by Magublafix** [comment]
jstack while pool-5-thread-1 was parked.

[jstack.txt](https://github.com/mp911de/logstash-gelf/files/1471206/jstack.txt)

**Comment by mp911de** [comment]
Thanks a lot. The stack dump shows a lot of event loop threads being idle. `sun.misc.Unsafe.park(…)` puts a thread in idle state doing actually nothing or waiting, depending on the context. Having idle threads isn't an issue in the first place. It gets an issue if you have a lot of threads (where `a lot` correlates with any number greater your CPU cores) so your operating system needs to do [context switching](https://en.wikipedia.org/wiki/Context_switch) to time share your CPU between threads.

Ideally, the number of threads matches the number of CPU cores. That's not possible with most operating systems because each operating system spins up a gazillion of services of which each one is running on one or more threads. Same applies to application servers. Because of the way application server, more specifically servlet-based containers, work, they require a thread for each request. If you would reduce the number of thread to the number of CPU cores (say 16) you would max out your application with 16 concurrent requests (not counting threads which are required to keep the server functional with monitoring, garbage collections, …).

Regarding your original question, it depends on how you measure CPU time. Seen from an availability perspective, the thread is blocked with waiting until a new task comes in. Realistically, this wait is terminated as soon as a task comes in so the thread can do actually useful stuff.

**Comment by Magublafix** [comment]
Hi @mp911de,

Thank you for the detailed answer, I have to discuss this with our developers.

The thing which still is not clear to me is why the cpu usage is that high (e.g. in top)  if the thread is just idle. And why the cpu is increasing under load altough the thread is within the park() method most of the time according to dynatrace.

![20171114_top](https://user-images.githubusercontent.com/4953529/32787861-f13f9016-c957-11e7-8e32-54f3994be6a7.PNG)

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by Magublafix** [comment]
Hi @mp911de,
Sorry for the late reply.

I found that the high cpu-consumption in park() method seems to be a measuring error.
https://answers.dynatrace.com/questions/174643/method-used-for-cpu-samplingprofiling-in-dynatrace.html

According to the thread i posted above the results are better with higher sampling rates. So i tried this and indeed the park() times decreased.
Nevertheless, the gelf-thread seems to be the top consumer.
![20180202_threads](https://user-images.githubusercontent.com/4953529/35728664-3c0b69d6-0804-11e8-8bfa-326630a16958.PNG)

Can you see someting suspicious in this execution tree?
![20180202_gelfcpu](https://user-images.githubusercontent.com/4953529/35728744-7426e7b4-0804-11e8-96e9-7f0665ce0598.PNG)

I'll attach an excel file with the whole cpu-sample of this thread.



regards,
Gerald
