### ISSUE TITLE
Groovy logback integration

### ISSUE THREAD

**Issue by fadjer** [mp911de/logstash-gelf#128]
Hi,

Please add it to your documentation:

import biz.paluch.logging.gelf.logback.GelfLogbackAppender
import ch.qos.logback.classic.AsyncAppender

// Graylog appender 
appender("GRAYLOG", GelfLogbackAppender) {
	host = "udp:11.16.15.69"
	port = 12206
	version = "1.1" 
	facility = "AppN" 
	extractStackTrace = true
	filterStackTrace = false
	timestampPattern = "yyyy-MM-dd HH:mm:ss,SSSS"
	maximumMessageSize = 8192
}

def grayLogAppender = appenderList.find { it -> it.name == "GRAYLOG" }

appender("ASYNC_GRAYLOG", AsyncAppender) {
    queueSize = 512
    appender = grayLogAppender
}

root(INFO, ["STDOUT", "FILE", "ASYNC_GRAYLOG"])

**Comment by mp911de** [comment]
Thanks for the hint. You're the first person asking for Groovy-based config. I don't have enough experience with Groovy to be comfortable what I put in the docs, therefore, I wouldn't be able to reason about why this piece of code should or shouldn't be the way it is.

Because of this rationale, I won't add the bits to the docs. Maybe I'll revisit this topic at a later time.
