### ISSUE TITLE
Feature Request: Allow complex  JSON object as additionalField

### ISSUE THREAD

**Issue by tanakos** [mp911de/logstash-gelf#133]
Currently the additionalFields only allow the addition of a key/value  json.
Sometime it might be useful to have a  more complex object as value.
A property such as complexFields with a comma separated as key,value. Such as 

param name="complexFields" value="fieldName1=fieldValue1,fieldName2=fieldValue2" 
param name="complexFieldName" value="complexField" 

The message will look like that:

{
    "LoggerName": "org.wildfly.extension.undertow",
    "short_message": "WFLYUT0008: Undertow HTTP listener default suspending",
    "level": "6",
    "Time": "2015-08-11 21:25:32,0734",
    "Severity": "INFO",
    "MessageParam1": "default",
    "Thread": "MSC service thread 1-6",
    "SourceMethodName": "stopListening",
    "MessageParam0": "HTTP",
    "full_message": "WFLYUT0008: Undertow HTTP listener default suspending",
    "SourceSimpleClassName": "HttpListenerService",
    "SourceClassName": "org.wildfly.extension.undertow.HttpListenerService",
    "facility": "java-test",
    "timestamp": "1439321132.734",
    **"complexField": {"fieldName1":  "fieldValue1",  "fieldName2": "fieldValue2"}**
}

Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [ ] You specify the logstash-gelf version and environment so it's obvious which version is affected
- [ ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by mp911de** [comment]
Thanks for the ticket. This feature won't happen because of multiple reasons:

1. It's hard to represent the configuration with each supported logging framework/integration.
2. This is an additional configuration which increases overall complexity and not quite straightforward to configure. Ideally, you want to include some dynamics (values from system properties, log events, MDC, …) and that requires some sort of evaluation.
3. There are already loggers that support specific complex objects.
4. Feel free to fork the library and add that feature in your own fork. You can always merge upstream changes into your own fork if you like to do so.
