### ISSUE TITLE
Best practices using a logstash cluster

### ISSUE THREAD

**Issue by Verdoso** [mp911de/logstash-gelf#135]
Hey there,

I just stated using logstash-gelf and my experiments so far have worked nicely. However, I'm now trying to deploy it in a real set up where I plan to have a logstash cluster and seeing that the udp:host setting seems to allow just specifying one host, I wonder how is that usually done with logstash-gelf as I'm probably not the first one to have to do so.

Do people change to other protocol paying the performance hit? Add a UDP proxy in front of the logstash cluster? I'm using Fabio as a load balancer, dynamically configured from Consul, but unfortunately it has no UDP support yet. I would rather not add another piece to the architecture if I can avoid it.

Any recommended or tested way of doing it?
Thanks!

**Comment by mp911de** [comment]
You can use only a single host. If you want to distribute your logs to a highly available target, then you can use:

1. Load balancers that forward UDP, TCP, or even GELF via HTTP
2. Use Redis with Redis Sentinel

What's the motivation for going HA?

Strengthening the target isn't really going to help much since you can experience network partitions between your application server and the target. 

You might rather want to use a different tool that accounts for log submission progress: Write logs into a local file and use tools like file beat to ensure all data is sent. Logstash-gelf is a tool for online log submission and that comes with certain properties such as the possibility of network partitions.

**Comment by Verdoso** [comment]
Yeah, I understand that you might have issues anyway between the application server and the target, the main motivation in my case was being able to shutdown/disconnect a logstash server for upgrading/maintenance without having to change the targets at the application server side.

I have already checked filebeat and the like and in fact, I'm checking these kind of things to decide which approach would work better in my case, filebat or direct connection, so I was just asking in case someone had had a similar issue. Maybe moving to tcp would be enough, as I already have a proxy that can handle that and I can dynamically update it through consul.

Do you have any experience about using udp agains tcp¿ Is the performance difference big enough as to keep trying to use udp?

**Comment by Verdoso** [comment]
I'm testing with tcp and so far so good, when I set up the final cluster and do some tests with the load-balancer in front, I'll report back how it goes.
You can close it now if you wish.
Thanks
