### ISSUE TITLE
It ships a few log but wildfly dies after a while

### ISSUE THREAD

**Issue by romulus010689** [mp911de/logstash-gelf#235]
Hello,
Having trouble getting you plugin running. It streams a few logs to Graylog, but dies after a few Minutes with this errormessage:
https://gist.github.com/romulus010689/4fbd1885b78b04ad5d0902141d2a9d70

Using version 1.14.0 of the plugin with WildFly Full 18.0.1.Final

This is the configuration in standalone.xml of the wildfly:
https://gist.github.com/romulus010689/12ea4eedc2c480930916950a23e27ae3

I inject the config by using the CLI:
https://gist.github.com/romulus010689/b871eb6b23fd15eb58ce3e3e5820a5df

I have no idea how to debug this, since it say that config parameters are missing, however those parameters are available and obviously used since it is able to stream for a while.

Would be so glad if someone could help.

Regards,
Thomas

**Comment by mp911de** [comment]
I haven't seen that kind of issue yet. It looks like a malfunction of the WildFly logging subsystem as it tries to configure the log handler with invalid values (`Invalid GELF version: null, supported range: 1.0, 1.1`, `Invalid port number: 0, supported range: 1-65535`).

There are preceeding errors (`Failed to invoke setter setOverflowAction with value null`) and the later ones seem to be caused by the previous ones. I suggest filing a ticket at WildFly as we cannot do anything here.
