### ISSUE TITLE
Make logstash-gelf OSGI 4+ compatible

### ISSUE THREAD

**Issue by haltunbay** [mp911de/logstash-gelf#238]
Hi there I would like to use the logstash-gelf inside karaf or osgi but current version of jar is compiled with manifest version 1 which is not compatible with osgi therefore karaf. 

Thanks

Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [ ] You specify the logstash-gelf version and environment so it's obvious which version is affected
- [ ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by mp911de** [comment]
Thanks for reaching out.

There isn't anything special we do in terms for OSGi. Actually, we stayed away from anything that is OSGi related as we're not using OSGi in our projects and in previous cases, the build tooling turned out to be painful. Given the lack of experience, we do not want to provide anything OSGi specific because we cannot support it.
