### ISSUE TITLE
There is no way to remove closed JedisPool from RedisSenderPoolProvider#standalonePools

### ISSUE THREAD

**Issue by herrlado** [mp911de/logstash-gelf#246]
Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [ ] gelf-logstash-1.14.0
- [ ] We reconfigure log4j settings during the runtime with new `PropertyConfigurator().doConfigure(reader,`
            LogManager.getLoggerRepository());` The Commons pools gets closed in `biz.paluch.logging.gelf.intern.sender.GelfREDISSender#close` but `RedisSenderPoolProvider` still holds the closed `JedisPool`
When now the log4j properties is reconfigured  `RedisSenderPoolProvider` delivers a closed JedisPool.

On Closing JedisPool pool, it also must be removed from RedisSenderPoolProvider.

**Comment by mp911de** [comment]
Thanks for bringing up that issue. The problem is here that `RedisSenderPoolProvider` is a shared/static holder for various kinds of `JedisPool` instances. You can have multiple appenders that consume pools. If we close a pool because an appender gets closed, all other active appenders will see a closed `JedisPool`. 

I think we need something like a refcounter to track usage and close the actual pool. Instead of shutting down the `Pool`, we'd rather decrement the refcounter and if it reaches zero, then we can safely remove the pool from `RedisSenderPoolProvider`.

**Comment by herrlado** [comment]
ok, but if the JedisPool gets closed. how can other appenders use them? It is not any more usable, no? I have made a  fix as a pull request, to demonstrate the solution. On JedisPool#destroy, it gets removed from the RedisSenderPoolProvider

https://github.com/mp911de/logstash-gelf/pull/247/commits/b9563a212963cf0962a0501cbe3f326a00ddb7a0

**Comment by mp911de** [comment]
Thanks a lot. Reiterating on the issue, we need to track refcount, otherwise, other appenders will see a closed pool. I have a draft locally to fix the issue. Do you mind if we close #247 in favor of my refcnt implementation?

**Comment by herrlado** [comment]
yes ok in understand. Sure. Thanks

**Comment by mp911de** [comment]
The fix is now in place. Thanks for your help!
