### ISSUE TITLE
TCP logger reacts poorly to closed connection, drops messages

### ISSUE THREAD

**Issue by terrysuereth-glu** [mp911de/logstash-gelf#62]
We discovered this issue when directing our GELF messages (in a logback configuration) by TCP to an Amazon Web Services Elastic Load Balancer.  The default AWS ELB settings close an idle connection after 60 seconds.

When the connection between our application and the ELB timed out (i.e. was idle for 60 seconds), we could observe the following behavior in `tcpdump` captures:
* A GELF message sent to the ELB was rejected.  (The ELB responded with an RST reset packet.)
* A new connection to the ELB would subsequently be SYNchronized and acknowledged...
* ...but the initially-rejected message would not be re-sent.
* Additionally, any messages that might have occurred between the RST and SYN/ACK were dropped completely.

It appears as though the logger is appropriately re-establishing a dropped connection, but does not attempt to re-send a message that failed due to this error, and is also ignoring messages going to the logger during this re-establishment time.

We are using logstash-gelf 1.7.2; based on the release notes for 1.8.0, I don't necessarily expect an upgrade will affect this behavior.

An excerpt of our logback configuration (omitting specific hostnames and field names) is below.

```xml
    <appender name="graylog" class="biz.paluch.logging.gelf.logback.GelfLogbackAppender">
        <host>tcp:...</host>
        <port>12201</port>
        <version>1.1</version>
        <additionalFields>...</additionalFields>
        <includeFullMdc>true</includeFullMdc>
        <extractStackTrace>true</extractStackTrace>
        <filterStackTrace>true</filterStackTrace>
    </appender>

    <appender name="asyncGraylog" class="ch.qos.logback.classic.AsyncAppender">
        <queueSize>1024</queueSize>
        <appender-ref ref="graylog"/>
    </appender>
```

**Comment by mp911de** [comment]
Hi, 
thanks for the report and the detailed analysis. There are multiple issues here:

1. The appender does not retry to send failed messages. When an error occurs, the message is just not sent.
2. TCP keep-alive _could_ help to mitigate the timeout issue, but this is still no solution
3. If you need absolute reliability, either file logging or AMQP might be the better option for you

logstash-gelf was not built with a transport guarantee in mind but as a tool to perform realtime GELF submission without consuming too much performance. Adding a retry mechanism to the TCP sender is possible but this will affect performance in failure scenarios.

Does this make sense?

**Comment by terrysuereth-glu** [comment]
I think so, but to clarify:

* Do you mean to say that the no-retry behavior is intentional?  I.e. Will this bug be rejected as "working as intended" -- directing what manner of workaround we look for.

* Your configuration examples for logback/etc. only mention the tcp, udp, and redis transports.  Is logback-gelf also compatible with other Graylog/GELF transports such as amqp or http?

**Comment by mp911de** [comment]
I see your point and I don't reject this ticket. It was just built that way and I need to come up with a solution how to configure retrying without harming/breaking anything.

logstash-gelf has only TCP, UDP and Redis transports. AMQP and HTTP are not supported. You could however build your own transport since logstash-gelf allows custom senders using the ServiceLoader mechanism (for `biz.paluch.logging.gelf.intern.GelfSenderProvider`) if that helps you finding a better solution than TCP with configurable retries.

**Comment by terrysuereth-glu** [comment]
I gotcha, thanks for the clarification.

Taking a look at the appender/sender execution chain, what hypothetically makes sense to me - not sure if this fits well in your architecture plan - would be for each appender to, if `gelfSender.sendMessage()` fails, check a configuration flag for `retryAttempts` (default 0) and then continue to call `sendMessage()` until either it succeeds or retries are exhausted.

While this would block for an inordinate time if the underlying transport is broken, a user can soften that blow by wrapping the GELF appender in an `AsyncAppender` as we've done in the logback example I mentioned above.

**Comment by mp911de** [comment]
I will add following options/configuration settings to support retries:

`tcp:hostname?readTimeout=10s&connectionTimeout=1000ms&deliveryAttempts=5&keepAlive=true`

* `readTimeout` Socket Read-Timeout (SO_TIMEOUT). The unit can be specified as suffix (see below). A timeout of zero is interpreted as an infinite timeout. Defaults to `2s`. 
* `connectionTimeout` Socket Connection-Timeout (SO_TIMEOUT). The unit can be specified as suffix (see below). A timeout of zero is interpreted as an infinite timeout. Defaults to `2s`.
* `deliveryAttempts` Number of Delivery-Attempts. Will retry to deliver the message and reconnect if necessary. A number of zero is interpreted as an infinite attempts. Defaults to `1`.   
* `keepAlive` Enable TCP keepAlive. Defaults to `false`. 


The options will be TCP-sender specific because because UDP has no retries and I plan to switch also the Redis driver which is more resilient by default.

**Comment by terrysuereth-glu** [comment]
That sounds excellent and more than sufficient.  Thanks!

**Comment by mp911de** [comment]
Implemented.

**Comment by sergiomahs** [comment]
@mp911de Do you have any estimated date for the 1.8.1 release?

Thanks in advance!

**Comment by mp911de** [comment]
My bad, 1.8.1 is past due by 8 days. Going to release 1.8.1 tomorrow. Thanks for the reminder.
