### ISSUE TITLE
Failed to configure handler GelfLogger on Logger on JBoss AS 7

### ISSUE THREAD

**Issue by kgoedert** [mp911de/logstash-gelf#66]
Hi,

managed to get the logger working and sending messages to graylog in a wildfly 9 instance. Now I would like to do the same with a JBoss AS7.

I copied the module to the appropriate location, and on standalone.xml I have this:

```
<custom-handler name="GelfLogger" class="biz.paluch.logging.gelf.jboss7.JBoss7GelfLogHandler" module="biz.paluch.logging">
				<level name="INFO" />
				<properties>
					<property name="host" value="udp:10.1.1.10" />
					<property name="port" value="12201" />
					<property name="version" value="1.1" />
					<property name="facility" value="jboss7-kelly" />
					<property name="extractStackTrace" value="true" />
					<property name="filterStackTrace" value="false" />
					<property name="mdcProfiling" value="true" />
					<property name="timestampPattern" value="yyyy-MM-dd HH:mm:ss,SSSS" />
					<property name="maximumMessageSize" value="8192" />

					<!-- This are static fields -->
					<property name="additionalFields" value="fieldName1=fieldValue1,fieldName2=fieldValue2" />
					<!-- Optional: Specify field types -->
					<property name="additionalFieldTypes" value="fieldName1=String,fieldName2=Double,fieldName3=Long" />

					<!-- This are fields using MDC -->
					<property name="mdcFields" value="mdcField1,mdcField2" />
					<property name="dynamicMdcFields" value="mdc.*,(mdc|MDC)fields" />
					<property name="includeFullMdc" value="true" />
				</properties>
			</custom-handler>
```
and

```
<root-logger>
                <level name="INFO"/>
                <handlers>
                    <handler name="CONSOLE"/>
                    <handler name="FILE"/>
					<handler name="GelfLogger"/>
                </handlers>
  </root-logger>
```
But nothing is sent to the graylog server. If I add configurations to the logging.properties file as I did to wildfly, I get this message on Jboss console log:

`Failed to configure handler GelfLogger on Logger '' in context org.jboss.logmanager.LogContext@7a10b9ed: Handler GelfLogger could not be instantiated`

The logging.properties is as follows:

```
handler.GelfLogger=biz.paluch.logging.gelf.jboss7.JBoss7GelfLogHandler
handler.GelfLogger.module=biz.paluch.logging
handler.GelfLogger.level=INFO
handler.GelfLogger.formatter=GelfLogger
handler.GelfLogger.properties=host,port,version,facility,extractStackTrace,filterStackTrace,mdcProfiling,timestampPattern,maximumMessageSize,additionalFields,additionalFieldTypes,mdcFields,dynamicMdcFields,includeFullMdc
handler.GelfLogger.host=udp\:10.1.1.10
handler.GelfLogger.port=12201
handler.GelfLogger.version=1.1
handler.GelfLogger.facility=wildfly79
handler.GelfLogger.extractStackTrace=true
handler.GelfLogger.filterStackTrace=false
handler.GelfLogger.mdcProfiling=true
handler.GelfLogger.timestampPattern=yyyy-MM-dd HH\:mm\:ss,SSSS
handler.GelfLogger.maximumMessageSize=8192
handler.GelfLogger.additionalFields=fieldName1\=fieldValue1,fieldName2\=fieldValue2
handler.GelfLogger.additionalFieldTypes=fieldName1\=String,fieldName2\=Double,fieldName3\=Long
handler.GelfLogger.mdcFields=mdcField1,mdcField2
handler.GelfLogger.dynamicMdcFields=mdc.*,(mdc|MDC)fields
handler.GelfLogger.includeFullMdc=true

logger.handlers=FILE,CONSOLE,GelfLogger
```

What am I missing?

**Comment by mp911de** [comment]
Which version of JBoss 7 do you use? Between some versions (mostly JBoss EAP-related) the default module organization scheme from non-layered to layered (`modules/system/layers/base`).

Do you see more of the `Handler GelfLogger could not be instantiated` exception, maybe some stack trace?

**Comment by kgoedert** [comment]
I use JBoss AS 7.1.1 the community version, not the EAP.
No I don't see any other messages, I even set all the log levels to debug, and there is nothing else. 
I also, don't have anything else, configured in this instance. I just downloaded it from the jboss site.

**Comment by mp911de** [comment]
I found the issue with JBoss AS 7.1.1 which are actually multiple issues:

1. JBoss AS 7.1.1 does not update the `logging.properties` (unlike future versions like WildFly), so you need to add the logger to `logging.properties` either using the admin tools or manually, like you did
2. The logmanager (1.2.2) does not care about the line `handler.GelfLogger.module=biz.paluch.logging`. The class cannot be found, this needs to be fixed manually by editing `modules/org/jboss/logmanager/main/module.xml` and adding a dependency to `<module name="biz.paluch.logging"/>` (see example below).
3. There's a line, `handler.GelfLogger.formatter=GelfLogger` which then leads to a failure. Simply remove this line.
4. logstash-gelf introduced since version 1.5.1 an incompatibility to the older JBoss logmanager versions, you need to use [1.5.0](https://github.com/mp911de/logstash-gelf/releases/tag/logstash-gelf-1.5.0) or earlier versions. Please check whether this works for you.

Once you have removed all these issues, it works, but the MDC contains values only from log4j (that's the 1.5.0/1.5.1 incompatibility).


**module.xml**
```xml
<module xmlns="urn:jboss:module:1.1" name="org.jboss.logmanager">
    <resources>
        <resource-root path="jboss-logmanager-1.2.2.GA.jar"/>
        <!-- Insert resources here -->
    </resources>

    <dependencies>
        <module name="biz.paluch.logging"/>
    </dependencies>
</module>
```

**Comment by kgoedert** [comment]
I worked. Thanks!
