### ISSUE TITLE
Handling Long in GelfUtil.addMdcProfiling

### ISSUE THREAD

**Issue by prlj13** [mp911de/logstash-gelf#73]
It looks like handling a Long in GelfUtil.addMdcProfiling isn't done properly.  There's a couple of ways to fix it.  I'd add an else to the _requestStartMs instanceof Long_ (and removing timestamp == -1 is possible too).

Resulting in something like this:
  if (instanceof Long) {...} else if (instanceof String) {...} else {return;}

**Comment by mp911de** [comment]
Could you elaborate what you mean by not properly? The code could be improved but is there a bug?

**Comment by prlj13** [comment]
If requestStartMs is a Long, which it looks like addMdcProfiling is supposed to support, then the value is ignored and the duration isn't added to the message.

**Comment by mp911de** [comment]
`requestStartMs` must be in any case numeric and can be stored within the MDC either as `long` (`Long`) or as `String`. The latter is used with slf4j's MDC. (That's just fyi).

You're totally right, the bug is so obvious that I haven't seen it for years now. Do you want to send in a PR or should I take care of it?

**Comment by prlj13** [comment]
I'm a newbie (not setup with GIT, just reviewing the source), so I'll let you take care of it.

**Comment by mp911de** [comment]
Thanks for the bug report, fixed with a916fd1.
