### ISSUE TITLE
JBoss AS7 logging - Disable MessageParam# splitting.

### ISSUE THREAD

**Issue by djmoky83** [mp911de/logstash-gelf#87]
Using JBoss AS7 logging handler, will split params in the message to "MessageParam#={value}" 

Please have a configuration to disable this.

**Comment by mp911de** [comment]
How about a Pull-Request? `MessageParam` affects only `java.util.logging` and it's subtypes.

**Comment by birnbuazn** [comment]
@djmoky83 You can always filter out the MessageParam fields using logstash

`filter {
	mutate {
		remove_field => ["MessageParam0", "MessageParam1", "MessageParam2", "MessageParam3", "MessageParam4", "MessageParam5", "MessageParam6", "MessageParam7", "MessageParam8", "MessageParam9" ]
	}
}`

**Comment by sohilpatel** [comment]
Hi @birnbuazn,

That's correct what you said above but sometimes number format exception/other kind of exceptions occur in the ELK logs because of that. 
e.g. MapperParsingException[failed to parse [MessageParam4]]; nested: NumberFormatException[For input string: "[]"];

 It would be avoidable if there is a configuration to disable all message params.

**Comment by birnbuazn** [comment]
@sohilpatel These exceptions only occur within [ElasticSearch](http://stackoverflow.com/a/27170497/287138), if you do not filter out the fields. Whether you do that within the GELF logger or within Logstash is irrelevant.

**Comment by sohilpatel** [comment]
Hi @birnbuazn,

Yes you are correct. I updated my filter configuration properly and exception disappeared. Thanks for that. :)

**Comment by mp911de** [comment]
That's implemented now with 10eae2f.
